// add-icon-registry (#85, design.md D1): die eine Icon-Registry des Clients - ein fester
// Name (eine Rolle, keine Bildbeschreibung) je Bild aus `lucide-react`. `Icon`/`IconButton`
// (`Icon.tsx`) und die Karte (`icon-svg.ts`, `map/canvas.ts`) zeichnen ausschliesslich ueber
// diese Tabelle; ein Bildtausch aendert genau eine Zeile hier. Benannte Importe (baumschuett-
// elbar) - kein Namespace-Import, kein `lucide-react/dist/...` (proposal.md, design.md D1).
//
// Abweichung von design.md D1: `dragon` sollte `Snake` zeigen, das es in der installierten
// Version 1.45.0 von `lucide-react` nicht gibt (kein Drache und keine Schlange im Katalog).
// Naechstliegende Form: `Worm` (geschwungener Koerper) - Tausch im Implementer-Summary
// genannt, im App-Test zu beurteilen (design.md "Risks").
import {
  ArrowDownToLine,
  Ban,
  BatteryLow,
  Biohazard,
  BowArrow,
  Brush,
  Bug,
  Check,
  ChevronDown,
  ChevronLeft,
  CircleDot,
  CircleHelp,
  CircleOff,
  CloudFog,
  Crown,
  EarOff,
  Ellipsis,
  Eye,
  EyeOff,
  Flame,
  Frown,
  Ghost,
  Hand,
  Heart,
  Info,
  LibraryBig,
  Link,
  Lock,
  LogOut,
  Map,
  Moon,
  Mountain,
  PawPrint,
  Pause,
  Pencil,
  Play,
  Plus,
  Ruler,
  Settings,
  Shield,
  Skull,
  Sparkles,
  Square,
  Sword,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  WandSparkles,
  Worm,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Genau die 54 Registry-Namen, in der Reihenfolge aus `specs/ui-icons/spec.md`
 * ("Registry-Namen"): Oberflaeche, Symbolkatalog, Zustandskatalog. */
export const ICON_NAMES = [
  // Oberflaeche
  'add',
  'back',
  'ban',
  'check',
  'chevronDown',
  'close',
  'delete',
  'draw',
  'edit',
  'end',
  'fog',
  'help',
  'hide',
  'info',
  'library',
  'lock',
  'logout',
  'map',
  'measure',
  'more',
  'pause',
  'players',
  'reveal',
  'settings',
  'start',
  'token',
  'upload',
  'user',
  'warning',
  // Symbolkatalog
  'fighter',
  'guardian',
  'undead',
  'dragon',
  'mage',
  'archer',
  'royal',
  'beast',
  'vermin',
  'fire',
  // Zustandskatalog
  'blinded',
  'charmed',
  'deafened',
  'exhausted',
  'frightened',
  'grappled',
  'incapacitated',
  'invisible',
  'paralyzed',
  'petrified',
  'poisoned',
  'prone',
  'restrained',
  'stunned',
  'unconscious',
] as const

export type IconName = (typeof ICON_NAMES)[number]

/** Name -> `lucide-react`-Komponente (design.md D1, verbindliche Zuordnungstabelle). */
export const ICON_REGISTRY: Record<IconName, LucideIcon> = {
  add: Plus,
  back: ChevronLeft,
  ban: Ban,
  check: Check,
  chevronDown: ChevronDown,
  close: X,
  delete: Trash2,
  draw: Brush,
  edit: Pencil,
  end: Square,
  fog: CloudFog,
  help: CircleHelp,
  hide: EyeOff,
  info: Info,
  library: LibraryBig,
  lock: Lock,
  logout: LogOut,
  map: Map,
  measure: Ruler,
  more: Ellipsis,
  pause: Pause,
  players: Users,
  reveal: Eye,
  settings: Settings,
  start: Play,
  token: CircleDot,
  upload: Upload,
  user: User,
  warning: TriangleAlert,

  fighter: Sword,
  guardian: Shield,
  undead: Skull,
  dragon: Worm,
  mage: WandSparkles,
  archer: BowArrow,
  royal: Crown,
  beast: PawPrint,
  vermin: Bug,
  fire: Flame,

  blinded: EyeOff,
  charmed: Heart,
  deafened: EarOff,
  exhausted: BatteryLow,
  frightened: Frown,
  grappled: Hand,
  incapacitated: CircleOff,
  invisible: Ghost,
  paralyzed: Zap,
  petrified: Mountain,
  poisoned: Biohazard,
  prone: ArrowDownToLine,
  restrained: Link,
  stunned: Sparkles,
  unconscious: Moon,
}
