// add-icon-registry (#85, design.md D1): die eine Icon-Registry des Clients - ein fester
// Name (eine Rolle, keine Bildbeschreibung) je Bild aus `lucide-react`. `Icon`/`IconButton`
// (`Icon.tsx`) und die Karte (`icon-svg.ts`, `map/canvas.ts`) zeichnen ausschliesslich ueber
// diese Tabelle; ein Bildtausch aendert genau eine Zeile hier. Benannte Importe (baumschuett-
// elbar) - kein Namespace-Import, kein `lucide-react/dist/...` (proposal.md, design.md D1).
//
// Abweichung von design.md D1: `dragon` sollte `Snake` zeigen, das es in der installierten
// Version 1.45.0 von `lucide-react` nicht gibt (kein Drache und keine Schlange im Katalog).
// Naechstliegende Form: `Worm` (geschwungener Koerper) - Tausch im Implementer-Summary
// genannt, im App-Test zu beurteilen (design.md "Risks").
//
// session-bar (#93, design.md D7): `copy` (Lucide `Copy`) nach `close` - die Registry traegt
// jetzt 55 Namen.
//
// add-token-cards (#95, design.md D8): `locate` (Lucide `LocateFixed`) zwischen `library` und
// `lock` - die Registry traegt jetzt 56 Namen.
//
// ui-toolbar (#96, design.md D1, spec.md "Registry"): vier neue Namen fuer die
// Werkzeugleisten von Fog- und Anmerkungsverwaltung - `move` (Lucide `Move`, Bewegen/
// Schwenken), `area` (Lucide `BoxSelect`, Bereich markieren), `circle` (Lucide `Circle`,
// Kreis), `angle` (Lucide `Angle`, Winkel). Alphabetisch in die Oberflaeche einsortiert -
// die Registry traegt jetzt 60 Namen.
import {
  Angle,
  ArrowDownToLine,
  Ban,
  BatteryLow,
  Biohazard,
  BowArrow,
  BoxSelect,
  Brush,
  Bug,
  Check,
  ChevronDown,
  ChevronLeft,
  Circle,
  CircleDot,
  CircleHelp,
  CircleOff,
  CloudFog,
  Copy,
  Crown,
  EarOff,
  Ellipsis,
  Eye,
  EyeOff,
  Flame,
  Frown,
  Ghost,
  Hand,
  Heart,
  Info,
  LibraryBig,
  Link,
  LocateFixed,
  Lock,
  LogOut,
  Map,
  Moon,
  Mountain,
  Move,
  PawPrint,
  Pause,
  Pencil,
  Play,
  Plus,
  Ruler,
  Settings,
  Shield,
  Skull,
  Sparkles,
  Square,
  Sword,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  WandSparkles,
  Worm,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Genau die 60 Registry-Namen, in der Reihenfolge aus `specs/ui-icons/spec.md`
 * ("Registry-Namen"): Oberflaeche, Symbolkatalog, Zustandskatalog. */
export const ICON_NAMES = [
  // Oberflaeche
  'add',
  'angle',
  'area',
  'back',
  'ban',
  'check',
  'chevronDown',
  'circle',
  'close',
  'copy',
  'delete',
  'draw',
  'edit',
  'end',
  'fog',
  'help',
  'hide',
  'info',
  'library',
  'locate',
  'lock',
  'logout',
  'map',
  'measure',
  'more',
  'move',
  'pause',
  'players',
  'reveal',
  'settings',
  'start',
  'token',
  'upload',
  'user',
  'warning',
  // Symbolkatalog
  'fighter',
  'guardian',
  'undead',
  'dragon',
  'mage',
  'archer',
  'royal',
  'beast',
  'vermin',
  'fire',
  // Zustandskatalog
  'blinded',
  'charmed',
  'deafened',
  'exhausted',
  'frightened',
  'grappled',
  'incapacitated',
  'invisible',
  'paralyzed',
  'petrified',
  'poisoned',
  'prone',
  'restrained',
  'stunned',
  'unconscious',
] as const

export type IconName = (typeof ICON_NAMES)[number]

/** Name -> `lucide-react`-Komponente (design.md D1, verbindliche Zuordnungstabelle). */
export const ICON_REGISTRY: Record<IconName, LucideIcon> = {
  add: Plus,
  angle: Angle,
  area: BoxSelect,
  back: ChevronLeft,
  ban: Ban,
  check: Check,
  chevronDown: ChevronDown,
  circle: Circle,
  close: X,
  copy: Copy,
  delete: Trash2,
  draw: Brush,
  edit: Pencil,
  end: Square,
  fog: CloudFog,
  help: CircleHelp,
  hide: EyeOff,
  info: Info,
  library: LibraryBig,
  locate: LocateFixed,
  lock: Lock,
  logout: LogOut,
  map: Map,
  measure: Ruler,
  more: Ellipsis,
  move: Move,
  pause: Pause,
  players: Users,
  reveal: Eye,
  settings: Settings,
  start: Play,
  token: CircleDot,
  upload: Upload,
  user: User,
  warning: TriangleAlert,

  fighter: Sword,
  guardian: Shield,
  undead: Skull,
  dragon: Worm,
  mage: WandSparkles,
  archer: BowArrow,
  royal: Crown,
  beast: PawPrint,
  vermin: Bug,
  fire: Flame,

  blinded: EyeOff,
  charmed: Heart,
  deafened: EarOff,
  exhausted: BatteryLow,
  frightened: Frown,
  grappled: Hand,
  incapacitated: CircleOff,
  invisible: Ghost,
  paralyzed: Zap,
  petrified: Mountain,
  poisoned: Biohazard,
  prone: ArrowDownToLine,
  restrained: Link,
  stunned: Sparkles,
  unconscious: Moon,
}
